name: "OZ - Rewards"
main: de.omegazirkel.risingworld.Rewards
version: 0.3.10
author: "Maik 'Devidian' Laschober"
team: "Omega Zirkel"
description: "Login, combat, and lightning wallet rewards"
license: N/A
website: https://api.github.com/repos/Devidian/rw-plugin-oz-rewards/releases/latest
loadorder: 0
