name: "OZ - Rewards"
main: de.omegazirkel.risingworld.Rewards
version: 0.3.1
author: "Maik 'Devidian' Laschober"
team: "Omega Zirkel"
description: "Login, combat, and lightning wallet rewards"
license: N/A
website: N/A
loadorder: 0
